
/****** Object:  Database [PRUEBATECNICANELSONREYES]    Script Date: 9/5/2024 08:52:09 ******/

CREATE DATABASE [PRUEBATECNICANELSONREYES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRUEBATECNICANELSONREYES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PRUEBATECNICANELSONREYES.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRUEBATECNICANELSONREYES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PRUEBATECNICANELSONREYES_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT


GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRUEBATECNICANELSONREYES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET RECOVERY FULL 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET  MULTI_USER 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PRUEBATECNICANELSONREYES', N'ON'
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET QUERY_STORE = OFF
GO
USE [PRUEBATECNICANELSONREYES]
GO
/****** Object:  Table [dbo].[Categorias]    Script Date: 9/5/2024 08:52:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorias](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreCategoria] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Items]    Script Date: 9/5/2024 08:52:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Items](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreItem] [varchar](255) NULL,
	[Descripcion] [text] NULL,
	[Categoria_id] [int] NULL,
	[Precio] [decimal](18, 0) NULL,
	[Negocio_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Negocios]    Script Date: 9/5/2024 08:52:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Negocios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreNegocio] [varchar](255) NULL,
	[Descripcion] [text] NULL,
	[FechaCreacion] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 9/5/2024 08:52:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [varchar](255) NULL,
	[Apellidos] [varchar](255) NULL,
	[Tipo_id] [int] NULL,
	[Correo] [varchar](255) NULL,
	[contrasenia] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserTipos]    Script Date: 9/5/2024 08:52:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserTipos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreTipoUsuario] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD  CONSTRAINT [FK__Items__Categoria__2D27B809] FOREIGN KEY([Categoria_id])
REFERENCES [dbo].[Categorias] ([Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Items] CHECK CONSTRAINT [FK__Items__Categoria__2D27B809]
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD  CONSTRAINT [FK__Items__Negocio_i__2E1BDC42] FOREIGN KEY([Negocio_id])
REFERENCES [dbo].[Negocios] ([Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
ALTER TABLE [Negocios]
ADD Usuario_id INT,
CONSTRAINT FK_Usuario_Negocio FOREIGN KEY (Usuario_id) REFERENCES Users(Id);
GO
ALTER TABLE [dbo].[Items] CHECK CONSTRAINT [FK__Items__Negocio_i__2E1BDC42]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([Tipo_id])
REFERENCES [dbo].[UserTipos] ([Id])
GO
ALTER DATABASE [PRUEBATECNICANELSONREYES] SET  READ_WRITE 



INSERT INTO UserTipos(NombreTipoUsuario)
VALUES 
('ADMINISTRADOR'),
('CLIENTE')
;

INSERT INTO [dbo].[Users](Nombres,Apellidos,Tipo_id,Correo,contrasenia)
VALUES 
('NELSON ELIAS','REYES FLORES',1,'admin@gmail.com','$2a$10$TSiTcWyPwI.qoQ5knYRa4Oy9pRfjwz7INmhZZhXSegMv0pMiobb1G'),
('CESAR ANTONIO','LOPEZ SORTO',2,'cliente@gmail.com','$2a$10$TSiTcWyPwI.qoQ5knYRa4Oy9pRfjwz7INmhZZhXSegMv0pMiobb1G'),
('CRISTOBAL','SORIA PEREZ',2,'cristobalsoria@gmail.com','$2a$10$TSiTcWyPwI.qoQ5knYRa4Oy9pRfjwz7INmhZZhXSegMv0pMiobb1G');




INSERT INTO [dbo].[Negocios](NombreNegocio,Descripcion,FechaCreacion,Usuario_id)
VALUES 
('PUPUSAS ROSI','Pupuseria con los mejores precios','1995-12-31',2),
('Tacos Benito','Tacos de todo tipo, incluido de birria y mas','2009-11-10',3),
('COMEDOR EL VENCEDOR','El comedor con mejores desayunos ven y disfruta en familia','2023-08-05',3);

SELECT * FROM [Negocios]


INSERT INTO [dbo].[Categorias] (
	NombreCategoria
)VALUES 
('Entradas'),
('Platos principales'),
('Postres');

INSERT INTO [dbo].[Items] (
	NombreItem,Descripcion,Categoria_id,Precio,Negocio_id
)VALUES 
('Ensalada César','Mezcla de lechugas frescas',1,12.99,1),
('Pizza Margarita','Pizza con salsa de tomate',2,35.99,2),
('Tiramisú ','Postre italiano hecho con capas de bizcocho de café, mascarpone y cacao en polvo',3,17.99,3);

SELECT * FROM [dbo].[Users]
SELECT * FROM [dbo].[Items]
SELECT * FROM UserTipos
